# permissions for end users to view configmaps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: configmap-viewer-role
rules:
- apiGroups:
  - configmap-controller.cluster-config
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - configmap-controller.cluster-config
  resources:
  - configmaps/status
  verbs:
  - get
